// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'movie.freezed.dart';
// optional: Since our Movie class is serializable, we must add this line.
// But if Movie was not serializable, we could skip it.
part 'movie.g.dart';

@freezed
class Movie with _$Movie {
  const factory Movie({
    int? id,
    String? poster_path,
    String? title,
    String? overview,
    String? release_date,
    double? vote_average,
    String? original_language,
  }) = _Movie;

  factory Movie.fromJson(Map<String, Object?> json) => _$MovieFromJson(json);
}
